image: docker:latest

stages:
- build
- deploy

variables:
  DOCKER_DRIVER: overlay2

before_script:
- apk add --no-cache curl python3 py3-pip
- pip install awscli

build:
  stage: build
  script:
  - docker build -t my-nextjs-app .

deploy:
  stage: deploy
  script:
  - docker tag my-nextjs-app:latest <aws_account_id>.dkr.ecr.<region>.amazonaws.com/my-nextjs-repo:latest
  - $(aws ecr get-login --no-include-email --region <region>)
  - docker push <aws_account_id>.dkr.ecr.<region>.amazonaws.com/my-nextjs-repo:latest
  - aws elasticbeanstalk create-application-version --application-name my-nextjs-app --version-label v$CI_COMMIT_REF_NAME --source-bundle S3Bucket=my-nextjs-bucket,S3Key=my-nextjs-app-v$CI_COMMIT_REF_NAME.zip
  - aws elasticbeanstalk update-environment --environment-name my-nextjs-env --version-label v$CI_COMMIT_REF_NAME
  only:
  - main
